### TUTTE LE RACCOLTE RIFIUTI
GET http://127.0.0.1:8000/api/ HTTP/1.1

### NUOVA RACCOLTA RIFIUTI
POST http://127.0.0.1:8000/api/add HTTP/1.1
Content-Type: application/json

{
	"rifiuto": "Scorie nucleari",
	"istruzioni": "Disperdere nelle falde acquifere",
	"giorni": "Martedì e Mercoledì",
	"orario": "00.00-04.00"

}

### AGGIORNAMENTO RACCOLTA
PUT http://127.0.0.1:8000/api/raccolta/{idRiga} HTTP/1.1
Content-Type: application/json

{
	"rifiuto": "Rifiuto aggiornato",
	"istruzioni": "Istruzioni aggiornate",
	"giorni": "Giorni aggiornati",
	"orario": "Orario aggiornato"
}

### CANCELLAZIONE RACCOLTA
DELETE http://127.0.0.1:8000/api/raccolta/7

### RACCOLTA DIFFERENZIATA ODIERNA
GET http://127.0.0.1:8000/api/giorno/oggi/ HTTP/1.1

### RACCOLTE IN BASE AL TIPO DI MATERIALE
GET http://127.0.0.1:8000/api/raccolta/organico HTTP/1.1